### ISSUE TITLE
Voorkom het onnodig herhalen van code in CSS

### ISSUE THREAD

**Issue by joostf** [julia-stevens/connect-your-tribe-profile-card#8]
Bijvoorbeeld:

```css
#item1.active {
  visibility: visible;
}


#item2.active {
  visibility: visible;
}


#item3.active {
  visibility: visible;
}


#item4.active {
  visibility: visible;
}


#item5.active {
  visibility: visible;
}


#item6.active {
  visibility: visible;
}
```

Kan je ook zo oplossen:

```css
.active {
  visibilty:visible;
}
```
